### ISSUE TITLE
쿠버네티스 내부 서비스간 연결 불가

### ISSUE THREAD

**Issue by emg-c** [Limheonjun/spring-msa#5]
[root@k8s-master ~]# kubectl logs -f deployment-integration-678b7c9764-pzpzk
Setting Active Processor Count to 2
Calculating JVM memory based on 2182320K available memory
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -Xmx1780729K -XX:MaxMetaspaceSize=94390K -XX:ReservedCodeCacheSize=240M -Xss1M (Total Memory: 2182320K, Thread Count: 50, Loaded Class Count: 14251, Headroom: 0%)
Enabling Java Native Memory Tracking
Adding 128 container CA certificates to JVM truststore
Spring Cloud Bindings Enabled
Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties -XX:+ExitOnOutOfMemoryError -XX:ActiveProcessorCount=2 -XX:MaxDirectMemorySize=10M -Xmx1780729K -XX:MaxMetaspaceSize=94390K -XX:ReservedCodeCacheSize=240M -Xss1M -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+PrintNMTStatistics -Dorg.springframework.cloud.bindings.boot.enable=true

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.0)

2021-11-24 12:43:07.972  INFO 1 --- [           main] c.e.i.IntegrationServiceApplication      : Starting IntegrationServiceApplication using Java 11.0.13 on deployment-integration-678b7c9764-pzpzk with PID 1 (/workspace/BOOT-INF/classes started by cnb in /workspace)
2021-11-24 12:43:07.988  INFO 1 --- [           main] c.e.i.IntegrationServiceApplication      : No active profile set, falling back to default profiles: default
2021-11-24 12:43:13.582  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8093
2021-11-24 12:43:13.728  INFO 1 --- [           main] c.e.i.IntegrationServiceApplication      : Started IntegrationServiceApplication in 8.466 seconds (JVM running for 10.812)
finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8092; nested exception is io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8092
2021-11-24 13:36:33.743 ERROR 1 --- [or-http-epoll-2] a.w.r.e.AbstractErrorWebExceptionHandler : [fb131983-2]  500 Server Error for HTTP GET "/operate/5"

org.springframework.web.reactive.function.client.WebClientRequestException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8092; nested exception is io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8092
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141) ~[spring-webflux-5.3.13.jar:5.3.13]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoErrorSupplied] :
	reactor.core.publisher.Mono.error
	org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.wrapException(ExchangeFunctions.java:141)
Error has been observed at the following site(s):
	*__________Mono.error ? at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.wrapException(ExchangeFunctions.java:141)
	|_                    ? at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$exchange$4(ExchangeFunctions.java:106)
	*__Mono.onErrorResume ? at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.exchange(ExchangeFunctions.java:106)
	|_           Mono.map ? at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.exchange(ExchangeFunctions.java:107)
	|_         checkpoint ? Request to GET http://localhost:8092/multiply/5 [DefaultWebClient]
	|_ Mono.switchIfEmpty ? at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.lambda$exchange$7(DefaultWebClient.java:433)
	*__________Mono.defer ? at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.exchange(DefaultWebClient.java:430)
	|_       Mono.flatMap ? at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.exchangeToMono(DefaultWebClient.java:397)
	|_      Mono.doOnNext ? at com.emgc.integrationservice.service.MultiplyService.doMultiply(MultiplyService.java:24)
	|_     Mono.doOnError ? at com.emgc.integrationservice.service.MultiplyService.doMultiply(MultiplyService.java:25)
	*________Mono.flatMap ? at com.emgc.integrationservice.service.IntegrationService.doOperate(IntegrationService.java:42)
	|_           Mono.map ? at com.emgc.integrationservice.service.IntegrationService.doOperate(IntegrationService.java:47)
	|_      Mono.doOnNext ? at com.emgc.integrationservice.service.IntegrationService.doOperate(IntegrationService.java:49)
	|_       Mono.flatMap ? at com.emgc.integrationservice.service.IntegrationService.doOperate(IntegrationService.java:54)
	|_           Mono.map ? at com.emgc.integrationservice.service.IntegrationService.doOperate(IntegrationService.java:59)
	|_      Mono.doOnNext ? at com.emgc.integrationservice.service.IntegrationService.doOperate(IntegrationService.java:61)
	|_           Mono.map ? at com.emgc.integrationservice.service.IntegrationService.doOperate(IntegrationService.java:66)
	|_          Mono.from ? at org.springframework.http.codec.json.AbstractJackson2Encoder.encode(AbstractJackson2Encoder.java:149)
	|_           Mono.map ? at org.springframework.http.codec.json.AbstractJackson2Encoder.encode(AbstractJackson2Encoder.java:150)
	|_          Mono.flux ? at org.springframework.http.codec.json.AbstractJackson2Encoder.encode(AbstractJackson2Encoder.java:151)
	|_ Flux.singleOrEmpty ? at org.springframework.http.codec.EncoderHttpMessageWriter.write(EncoderHttpMessageWriter.java:129)
	|_ Mono.switchIfEmpty ? at org.springframework.http.codec.EncoderHttpMessageWriter.write(EncoderHttpMessageWriter.java:130)
	|_       Mono.flatMap ? at org.springframework.http.codec.EncoderHttpMessageWriter.write(EncoderHttpMessageWriter.java:134)
	|_   Mono.doOnDiscard ? at org.springframework.http.codec.EncoderHttpMessageWriter.write(EncoderHttpMessageWriter.java:140)
	|_                    ? at org.springframework.http.codec.EncoderHttpMessageWriter.write(EncoderHttpMessageWriter.java:217)
	|_                    ? at org.springframework.web.reactive.function.BodyInserters.lambda$write$13(BodyInserters.java:401)
	|_                    ? at org.springframework.web.reactive.function.BodyInserters.write(BodyInserters.java:398)
	|_                    ? at org.springframework.web.reactive.function.BodyInserters.lambda$writeWithMessageWriters$10(BodyInserters.java:380)
	|_                    ? at org.springframework.web.reactive.function.BodyInserters.lambda$fromPublisher$4(BodyInserters.java:185)
	|_                    ? at org.springframework.web.reactive.function.server.DefaultEntityResponseBuilder$DefaultEntityResponse.writeToInternal(DefaultEntityResponseBuilder.java:233)
	|_                    ? at org.springframework.web.reactive.function.server.DefaultServerResponseBuilder$AbstractServerResponse.writeTo(DefaultServerResponseBuilder.java:351)
	|_                    ? at org.springframework.web.reactive.function.server.support.ServerResponseResultHandler.handleResult(ServerResponseResultHandler.java:94)
	|_         checkpoint ? Handler com.emgc.integrationservice.router.IntegrationServiceRouter$$Lambda$469/0x000000010040a040@ce2eae5 [DispatcherHandler]
	|_ Mono.onErrorResume ? at org.springframework.web.reactive.DispatcherHandler.handleResult(DispatcherHandler.java:181)
	|_                    ? at org.springframework.web.reactive.DispatcherHandler.lambda$handle$2(DispatcherHandler.java:154)
	*________Mono.flatMap ? at org.springframework.web.reactive.DispatcherHandler.lambda$handleResult$5(DispatcherHandler.java:182)
	*________Mono.flatMap ? at org.springframework.web.reactive.DispatcherHandler.handle(DispatcherHandler.java:154)
	|_                    ? at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
	*__________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
	|_                    ? at org.springframework.web.server.handler.FilteringWebHandler.handle(FilteringWebHandler.java:59)
	|_                    ? at org.springframework.web.server.handler.WebHandlerDecorator.handle(WebHandlerDecorator.java:56)
	|_ Mono.onErrorResume ? at org.springframework.web.server.handler.ExceptionHandlingWebHandler.handle(ExceptionHandlingWebHandler.java:77)
	*__________Mono.error ? at org.springframework.web.server.handler.ExceptionHandlingWebHandler$CheckpointInsertingHandler.handle(ExceptionHandlingWebHandler.java:98)
	|_         checkpoint ? HTTP GET "/operate/5" [ExceptionHandlingWebHandler]
	|_                    ? at org.springframework.web.server.handler.ExceptionHandlingWebHandler.lambda$handle$0(ExceptionHandlingWebHandler.java:77)
Original Stack Trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141) ~[spring-webflux-5.3.13.jar:5.3.13]
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:414) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:304) ~[reactor-netty-http-1.0.13.jar:1.0.13]
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:172) ~[reactor-netty-core-1.0.13.jar:1.0.13]
		at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:477) ~[reactor-netty-core-1.0.13.jar:1.0.13]
		at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:401) ~[reactor-netty-core-1.0.13.jar:1.0.13]
		at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:554) ~[reactor-netty-core-1.0.13.jar:1.0.13]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.12.jar:3.4.12]
		at reactor.netty.transport.TransportConnector$MonoChannelPromise.tryFailure(TransportConnector.java:517) ~[reactor-netty-core-1.0.13.jar:1.0.13]
		at reactor.netty.transport.TransportConnector$MonoChannelPromise.setFailure(TransportConnector.java:471) ~[reactor-netty-core-1.0.13.jar:1.0.13]
		at reactor.netty.transport.TransportConnector.lambda$doConnect$7(TransportConnector.java:206) ~[reactor-netty-core-1.0.13.jar:1.0.13]
		at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:674) ~[netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:693) ~[netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8092
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoOnErrorResume] :
	reactor.core.publisher.Mono.onErrorResume
	reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:111)
Error has been observed at the following site(s):
	*__Mono.onErrorResume ? at reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:111)
	*________Mono.flatMap ? at reactor.netty.transport.TransportConnector.connect(TransportConnector.java:110)
	*_________Mono.create ? at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator.connectChannel(DefaultPooledConnectionProvider.java:513)
	|_          Mono.from ? at reactor.netty.internal.shaded.reactor.pool.PoolBuilder.from(PoolBuilder.java:61)
	|_                    ? at reactor.netty.internal.shaded.reactor.pool.DefaultPoolConfig.allocator(DefaultPoolConfig.java:158)
	*____________________ ? at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.acquire(SimpleDequePool.java:111)
	*_________Mono.create ? at reactor.netty.resources.PooledConnectionProvider.acquire(PooledConnectionProvider.java:105)
	|_                    ? at reactor.netty.tcp.TcpResources.acquire(TcpResources.java:161)
	|_                    ? at reactor.netty.http.client.HttpConnectionProvider.acquire(HttpConnectionProvider.java:45)
	*_________Mono.create ? at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:209)
	|_     Mono.retryWhen ? at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:270)
	*______Flux.concatMap ? at reactor.util.retry.RetrySpec.generateCompanion(RetrySpec.java:356)
	*____________________ ? at reactor.netty.http.client.HttpClientFinalizer._connect(HttpClientFinalizer.java:156)
	|_   Mono.flatMapMany ? at reactor.netty.http.client.HttpClientFinalizer.responseConnection(HttpClientFinalizer.java:101)
	|_          Flux.next ? at org.springframework.http.client.reactive.ReactorClientHttpConnector.connect(ReactorClientHttpConnector.java:113)
	|_    Mono.doOnCancel ? at org.springframework.http.client.reactive.ReactorClientHttpConnector.connect(ReactorClientHttpConnector.java:114)
	|_   Mono.doOnRequest ? at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.exchange(ExchangeFunctions.java:104)
	|_    Mono.doOnCancel ? at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.exchange(ExchangeFunctions.java:105)
Original Stack Trace:
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[netty-transport-native-unix-common-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[netty-transport-native-unix-common-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:320) ~[netty-transport-native-unix-common-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-classes-epoll-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

localhost:8092로 연결요청하는데 커넥션 거부 발생

**Comment by emg-c** [comment]
요청을 localhost:8092를 보내는 것으로 보아 ingress를 통해 integration-service에는 접근이 잘 되는 것으로 보임

localhost:8092는 로컬환경에서는 문제 없이 동작하나, 쿠버네티스 클러스터에서는 같은 Pod내부의 컨테이너끼리만 같은 ip를 공유함

따라서 현재 integration-service, division-service, multiply-service 각자 다른 파드에 생성되었기 때문에 localhost가 아닌 내부 ip 또는 dns를 사용하여 호출해야 할 것으로 보임
